# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20170711_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumb',
            field=models.CharField(default=b'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/12in-Vinyl-LP-Record-Angle.jpg/1200px-12in-Vinyl-LP-Record-Angle.jpg', max_length=300),
        ),
    ]
